name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to do?
      description: The problem or situation, and how you'd like the app to help.
    validations:
      required: true
  - type: dropdown
    id: where
    attributes:
      label: Where
      options: [Watch app, Tile or complication, Phone app, Other]
